const challange = '30 Days Of JavaScript'
console.log(challange)
console.log(challange.length)
const upperChallenge = challange.toUpperCase()
console.log(upperChallenge)
const lowerChallenge = challange.toLowerCase()
console.log(lowerChallenge)
console.log(challange.substring(0, 2))
console.log(challange.substring(3))
console.log(challange.includes('Script'))
console.log(challange.split())
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(','))
console.log(challange.replace('JavaScript','Python'))
console.log(challange.charAt(15))
console.log(challange.charCodeAt(challange.indexOf('J')))
console.log(challange.indexOf('a'))
console.log(challange.lastIndexOf('a'))
const because = 'You cannot end a sentence with because because because is a conjunction'
console.log(because.indexOf('because'))
console.log(because.lastIndexOf('because'))
console.log(because.search('because'))
const trim = '   whitespaces   '
console.log(trim.trim())
console.log(challange.startsWith('30'))
console.log(challange.endsWith('pt'))
console.log(challange.match(/a/gi))
console.log('30 Days Of '.concat('JavaScript'))
console.log(challange.repeat(2))